# ============================================================
# EchestPlus plugin configuration
# ============================================================

name: '${project.name}'
version: '${project.version}'
main: net.nightzy.echestplus.EChestPlusPlugin
api-version: '${apiVersion}'
authors: 
  - 'Drago <klaudiusz.wojtyczka@nightzy.net>'
  - 'AVI'
website: '${project.url}'
description: "EChestPlus - Supercharged Ender Chest Plugin"
softdepend:
  - ItemsAdder
# ============================================================
# Permissions
# ============================================================
permissions:
  nightzy.echestplus.admin:
    description: Allows access to /adminec command
    default: op

# ============================================================
# Commands
# ============================================================

commands:

  adminec:
    description: Admin commands for Ender Chest
    aliases:
      - aec
      - adminenderchest
    usage: /adminec <getItem|open|reload>
    permission: echestplus.admin
