# ============================================================
# EchestPlus plugin configuration
# ============================================================

name: 'EChestPlus'
version: '0.1-Prerelease.3'
main: net.nightzy.echestplus.EChestPlusPlugin
api-version: '1.21'
authors:
  - Drago <drago.klaudiusz@gmail.com>
website: 'https://nightzy.net'
description: "TBN"
# ============================================================
# Permissions
# ============================================================



# ============================================================
# Commands
# ============================================================

commands:
  giveupgrade:
    description: Gives Ender Chest upgrade item
    usage: /giveupgrade
