# ============================================================
# EchestPlus plugin configuration
# ============================================================

name: 'EchestPlus'
version: '26.1-Beta.1'
main: net.nightzy.echestplus.EChestPlusPlugin
api-version: '1.15'
authors:
  - Drago <klaudiusz.wojtyczka@nightzy.net>
  - AVI
website: 'https://nightzy.net'
description: "TBN"
# ============================================================
# Permissions
# ============================================================
permissions:
  nightzy.echestplus.admin:
    description: Allows access to /adminec command
    default: op

# ============================================================
# Commands
# ============================================================

commands:

  adminec:
    description: Admin commands for Ender Chest
    aliases:
      - aec
      - adminenderchest
    usage: /adminec <getItem|open|reload>
    permission: echestplus.admin
